
apiVersion: v1
kind: Service
metadata:
  name: :[name]:-svc
  namespace: :[namespace]:
  labels:
    app: :[name]:
spec:
  type: NodePort
  ports:
  - port: :[port]:
    targetPort: :[port]:
    name: http
  selector:
    app: :[name]:
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: :[name]:-deployment
  namespace: :[namespace]:
  labels:
    app: :[name]:
spec:
  selector:
    matchLabels:
      app: :[name]:
  template:
    metadata:
      labels:
        app: :[name]:
    spec:
      containers:
      - name: :[name]:
        image: :[image]:
        ports:
        - containerPort: :[port]:
        resources:
          limits:
            cpu: :[cpu-limits]:
            memory: :[memory-limits]:
          requests:
            cpu: :[cpu]:
            memory: :[memory]:

        readinessProbe:
          httpGet:
            path: /:[ingress-path]:/ready 
            port: :[port]:
          initialDelaySeconds: 2 
          periodSeconds: 5      
        livenessProbe:  
          httpGet:
            path: /:[ingress-path]:/ready 
            port: :[port]:
          initialDelaySeconds: 20 
          periodSeconds: 60  
---
# apiVersion: autoscaling.k8s.io/v2beta2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: :[name]:-hpa
#   namespace: :[namespace]:
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment 
#     name: :[name]:-deployment 
#   minReplicas: :[min-replicas]: 
#   maxReplicas: :[max-replicas]: 
#   metrics:
#   - type: Resource
#     resource:
#       name: cpu
#       targetAverageUtilization: :[cpu-percentage-scaling]: 
#   - type: Resource
#     resource:
#       name: memory
#       targetAverageUtilization: :[memory-percentage-scaling]: 